name: CI

on:
  pull_request:
    paths:
      - 'platform_android/**'

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew :authentication:connectedCheck
