name: CI

on:
  pull_request:
    paths:
      - 'platform_android/**'

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Create UI test commands
      run: |
        $commands="$(./.github/scripts/create_android_pr_ui_commands.sh)"
        echo "::set-env name=COMMANDS::$commands"
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ${{ env.COMMANDS }}
