name: CI

on:
  pull_request:
    paths:
      - 'native/KotlinIOS/Authentication/**'
jobs:
 
  test:
    name: Run all Unit Tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: |
          xcodebuild clean test -project KotlinIOS.xcodeproj -scheme Authentication -destination 'platform=iOS Simulator,name=iPhone 11' CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
